name: Go unit test
description: Run unit tests in Go
inputs:
  cover-path:
    description: Path to the coverprofile
    required: false
    default: ./cover.out
runs:
  using: composite
  steps:
    - name: Go unit test
      shell: bash
      run: |
        go test -count=1 -v ./... -coverprofile=${{ inputs.cover-path }} -covermode=atomic -coverpkg=./...
