name: Go lint
description: Lint via golangci-lint
runs:
  using: composite
  steps:
    - name: Go lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.5.0
        args: '--timeout 10m'
